### ISSUE TITLE
Could NOT find Libobs (missing: LIBOBS_LIB LIBOBS_INCLUDE_DIR) 

### ISSUE THREAD

**Issue by Alzy** [obsproject/obs-plugintemplate#1]
I've cloned the repo and followed the instructions on my Windows PC but my cmake-gui fails when I hit configure complaining that it can't find LIBOBS:

```
Could NOT find Libobs (missing: LIBOBS_LIB LIBOBS_INCLUDE_DIR) 
CMake Error at plugins/obs-midi2/external/FindLibObs.cmake:106 (message):
  Could not find the libobs library
Call Stack (most recent call first):
  plugins/obs-midi2/CMakeLists.txt:30 (include)
```

I've tried following other a couple other forums online to see what may be a fix and few suggested to building OBS first then pointing LIBOBS_LIB to the .lib file in my build/libobs/Release folder the other variable to the /libobs folder... HOWEVER after doing that and hitting configure the new entries in cmake disappear and I'm given the same error all over again...

**Comment by mrklkrl** [comment]
any solution for this? seeing the same thing.

**Comment by Fenrirthviti** [comment]
You need to specify

`LIBOBS_INCLUDE_DIR (path) : Libobs include folder`
`LIBOBS_LIB (filepath) : obs.lib path`

As cmake variables.

**Comment by mrklkrl** [comment]
specifically, with obs-studio's repo parallel to this repo, what worked for me was:

cmake .. \
    -DQTDIR=/usr/local/opt/qt \
    -DLIBOBS_INCLUDE_DIR="../../obs-studio/libobs" \
    -DLIBOBS_LIB="../../obs-studio/build/libobs/libobs.dylib" \
    -DOBS_FRONTEND_LIB="$(pwd)/../../obs-studio/build/UI/obs-frontend-api/libobs-frontend-api.dylib" \
    -DCMAKE_INSTALL_PREFIX="/usr" \
&& make -j4

**Comment by Fenrirthviti** [comment]
Going to close this as it's not really a bug or an issue, but a support request. If you are looking for further help, please use our Forums or Discord.

https://obsproject.com/help

**Comment by JairoBoss** [comment]
Try doing:
sudo apt install libobs-dev
