### ISSUE TITLE
RFC: Modify CMakeLists.txt to allow for building in or out of tree

### ISSUE THREAD

**Issue by cpyarger** [obsproject/obs-plugintemplate#10]
# Summary

I know with the current CI pipeline, the plugins get built out of tree, though personally, I prefer to build in tree as it makes building testing and debugging quite a bit easier. 

# Motivation

This would allow people to choose to build in or out of tree. 

# Drawbacks

Slightly more complex cmake for plugins. 

# Additional Information

Any additional information that may not be covered above that you feel is relevant. External links, references, examples, etc.

**Comment by RytoEX** [comment]
We have decided against this at this time.
