### ISSUE TITLE
macos plugin build failing to find util/dstr.h

### ISSUE THREAD

**Issue by EZ64cool** [obsproject/obs-plugintemplate#102]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

N/A

### Expected Behavior

macos builds should be able to include util/dstr.h without issue

### Current Behavior

macos fails build, stating it can't find util/dstr.h

### Steps to Reproduce

1. Create from template
2. Add `#include <util/dstr.h>` to plugin-main.c
3. Push changes

### Anything else we should know?

Links to builds failing on my current plugin
https://github.com/EZ64cool/obs-hadowplay/actions/runs/6884310748/job/18726554756

This came up whilst I've been trying to merge the latest template.

**Comment by EZ64cool** [comment]
I recreated a repositry with only these change as proof
https://github.com/EZ64cool/obs-template-test

**Comment by EZ64cool** [comment]
Found https://github.com/obsproject/obs-plugintemplate/issues/88 and will give it a go

**Comment by RytoEX** [comment]
@EZ64cool was this resolved for you?

**Comment by EZ64cool** [comment]
Yes thank you, updating to obs-studio 30 fixed the issue.
