### ISSUE TITLE
Created release does not use plugin name

### ISSUE THREAD

**Issue by CodeYan01** [obsproject/obs-plugintemplate#105]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

N/A

### Expected Behavior

Have the plugin name in the release title

### Current Behavior

![image](https://github.com/obsproject/obs-plugintemplate/assets/65320293/9ff693d6-0538-43b9-9e25-7006ea9b1221)

Creates a draft release titled OBS Studio. While it's fine because it is a draft, having a friendly name in buildspec.json would be great so that we don't have to change the title all the time. I already put 'media-playlist-source' as the name but being able to put 'Media Playlist Source' in release titles automatically would be useful.

### Steps to Reproduce

1. Push a tag to make a release
2. Check the draft release

**Comment by PatTheMav** [comment]
@CodeYan01 please check with the changes added by #109.

**Comment by CodeYan01** [comment]
Thanks, will report back when I get to it soon

**Comment by CodeYan01** [comment]
@PatTheMav 
![image](https://github.com/obsproject/obs-plugintemplate/assets/65320293/5b5a6161-5440-4d46-85e3-33d4c16b78cf)

Yes, it did use the plugin name in the release. But I think it would be great if we could specify a "pretty-name" in the buildspec that it will use in the release title and installer. Like for this one, I would prefer to see "Media Playlist Source" (title case and no dashes).

**Comment by PatTheMav** [comment]
@CodeYan01 good point, I updated the PR - the buildspec now contains a key `displayName` that can be used for this and the old `name` will be used as a fallback if the former is not set. Also allowed me to make the regular expression more specific.
