### ISSUE TITLE
RFC: Improve documentation on MacOS Signing 

### ISSUE THREAD

**Issue by cpyarger** [obsproject/obs-plugintemplate#11]
# Summary

Improve the documentation to include a step by step howto on setting up MacOS Signing

# Motivation

It took me days and multiple sources across the internet to stumble on how to get it working.

# Drawbacks

Not a thing

# Additional Information

Any additional information that may not be covered above that you feel is relevant. External links, references, examples, etc.

**Comment by RytoEX** [comment]
Do you have any specific examples of what parts you had to search for resources to complete? Do you have any specific examples of what resources you found helpful? We will try to add some relevant links to Apple documentation to the README and/or the wiki.

**Comment by cpyarger** [comment]
I am not sure anymore honestly, Its been nearly a year and a half since I created the issue, So Ill close this. and when next setting things up if I find anything confusing I'll make a PR with updated information.
