### ISSUE TITLE
RFC: Update MAC CI to check for secrets

### ISSUE THREAD

**Issue by cpyarger** [obsproject/obs-plugintemplate#12]
# Summary

Check for the existence of the required secrets for macOS signing. If they do not exist. skip those CI actions. 

# Motivation

The currently included CI pipeline breaks unless you have the ability and license to setup macOS signing and notarization.

A plugin template that includes a CI pipeline, should have that pipeline succeed when run without having to set up anything externally. 

# Drawbacks

Not sure I can think of one 

# Additional Information

Any additional information that may not be covered above that you feel is relevant. External links, references, examples, etc.

**Comment by RytoEX** [comment]
This appears to have been resolved in #15 and further adjusted in #19.
