### ISSUE TITLE
Unable to build on distros that don't support apt-get

### ISSUE THREAD

**Issue by nambona890** [obsproject/obs-plugintemplate#135]
### Operating System Info

Other

### Other OS

Nobara Linux 40

### OBS Studio Version

31.0.0-rc1

### OBS Studio Log URL

N/A

### Expected Behavior

The repo to build correctly after running the Linux build script.

### Current Behavior

Running the Linux build script results in the following output:
`=>   Check Linux build requirements`
`✖︎   No apt-get command found. Please install apt`

### Steps to Reproduce

1. Use a Linux distro that uses a package manager that isn't apt (instead uses dnf/yum/pacman), such as Fedora-based distros.
2. Run the Linux build script.

**Comment by RytoEX** [comment]
The build scripts in the `.github` directory are meant for CI only. They are not meant for local use.
