### ISSUE TITLE
make install does not install to a directory that is searched by OBS

### ISSUE THREAD

**Issue by ipatix** [obsproject/obs-plugintemplate#18]
### Operating System Info

Other

### Other OS

Debian Sid (64 bit)

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/WLp4Nql50comrVG6z

### Expected Behavior

When I compile the project template on Linux and use `make install` the plugin is installed to `/usr/local/lib/obs-plugins`. I would expect either OBS to load the plugin after doing this or I would expect `make install` to install the plugin to a directory that's actually searched by OBS.

### Current Behavior

OBS does not search `/usr/local/lib/obs-plugins/` and the `make install` command doesn't do what one would expect because the plugin is installed incorrectly. Installing the plugin to a path which is not searched appears to be pretty useless.

### Steps to Reproduce

1. Clone the project repository
2. `mkdir build && cd build`
3. `cmake ..`
4. `make`
5. `sudo make install`
6. Start OBS
7. Log file doesn't show the text that the template plugin writes to the log (i.e. plugin is not loaded)

**Comment by PatTheMav** [comment]
CMake assumes `/usr/local` as the default install prefix (`CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT` evaluates true then). If you want to use a different prefix, you have to pass it as `CMAKE_INSTALL_PREFIX` when configuring the project.

Alternatively you can install using `cmake --install <YOUR_BUILD_DIR> --prefix <YOUR_INSTALL_LOCATION>`.

Detecting different Linux distributions and their quirks is out of scope for this template and we leave it to plugin authors to extend it for their own projects. If you argue that OBS itself should be aware of these conventions and _also_ load plugins from `/usr/local`, feel free make such a feature request over there.

**Comment by ipatix** [comment]
If I get the time I will do as you suggest and open a PR over for obs-studio itself. Thanks!
