### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by Andrey-Arutiunian** [obsproject/obs-plugintemplate#20]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/eCGaQxWUEPnt64Qk

### Expected Behavior

Success Build

### Current Behavior

Failed build

### Steps to Reproduce

1. ```git clone https://github.com/obsproject/obs-plugintemplate.git```
2. ```cd obs-plugintemplate```
3. ```./CI/build-macos.sh```

### Anything else we should know?

I use bash.

Here is log:
  + Check macOS version...
  + Check Architecture...
  + Fetching version tags...
[obs-plugin] Installing Homebrew dependencies
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
kopia
==> Updated Formulae
Updated 13 formulae.
==> Updated Casks
Updated 14 casks.

Using cmake
Using ninja
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
[obs-plugin] Set up precompiled macOS OBS dependencies v2021-08-17
  + Download...
############################################################################################################################### 100,0%############################################################################################################################### 100,0%
  + macos-deps-2021-08-17-universal.tar.xz downloaded successfully and passed hash check
  + Unpack...
[obs-plugin] Set up precompiled dependency Qt v2021-08-17
  + Download...
############################################################################################################################### 100,0%############################################################################################################################### 100,0%
  + macos-deps-qt-2021-08-17-universal.tar.xz downloaded successfully and passed hash check
  + Unpack...
Cloning into '/Users/rxandrey/Tests/obs-studio'...
remote: Enumerating objects: 77875, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 77875 (delta 0), reused 0 (delta 0), pack-reused 77874
Receiving objects: 100% (77875/77875), 51.33 MiB | 5.20 MiB/s, done.
Resolving deltas: 100% (52534/52534), done.
Updating files: 100% (4509/4509), done.
Submodule 'plugins/enc-amf' (https://github.com/obsproject/obs-amd-encoder.git) registered for path 'plugins/enc-amf'
Submodule 'plugins/mac-syphon/syphon-framework' (https://github.com/palana/Syphon-Framework.git) registered for path 'plugins/mac-syphon/syphon-framework'
Submodule 'plugins/obs-browser' (https://github.com/obsproject/obs-browser.git) registered for path 'plugins/obs-browser'
Submodule 'plugins/obs-outputs/ftl-sdk' (https://github.com/Mixer/ftl-sdk.git) registered for path 'plugins/obs-outputs/ftl-sdk'
Submodule 'plugins/obs-vst' (https://github.com/obsproject/obs-vst.git) registered for path 'plugins/obs-vst'
Submodule 'plugins/win-dshow/libdshowcapture' (https://github.com/obsproject/libdshowcapture.git) registered for path 'plugins/win-dshow/libdshowcapture'
Cloning into '/Users/rxandrey/Tests/obs-studio/plugins/enc-amf'...
remote: Enumerating objects: 8222, done.        
remote: Counting objects: 100% (105/105), done.        
remote: Compressing objects: 100% (74/74), done.        
remote: Total 8222 (delta 34), reused 65 (delta 23), pack-reused 8117        
Receiving objects: 100% (8222/8222), 14.68 MiB | 1.36 MiB/s, done.
Resolving deltas: 100% (5720/5720), done.
Cloning into '/Users/rxandrey/Tests/obs-studio/plugins/mac-syphon/syphon-framework'...
remote: Enumerating objects: 453, done.        
remote: Total 453 (delta 0), reused 0 (delta 0), pack-reused 453        
Receiving objects: 100% (453/453), 393.37 KiB | 1.96 MiB/s, done.
Resolving deltas: 100% (306/306), done.
Cloning into '/Users/rxandrey/Tests/obs-studio/plugins/obs-browser'...
remote: Enumerating objects: 2876, done.        
remote: Counting objects: 100% (528/528), done.        
remote: Compressing objects: 100% (275/275), done.        
remote: Total 2876 (delta 294), reused 360 (delta 247), pack-reused 2348        
Receiving objects: 100% (2876/2876), 887.32 KiB | 3.40 MiB/s, done.
Resolving deltas: 100% (1899/1899), done.
Cloning into '/Users/rxandrey/Tests/obs-studio/plugins/obs-outputs/ftl-sdk'...
remote: Enumerating objects: 2720, done.        
remote: Total 2720 (delta 0), reused 0 (delta 0), pack-reused 2720        
Receiving objects: 100% (2720/2720), 895.99 KiB | 2.73 MiB/s, done.
Resolving deltas: 100% (1926/1926), done.
Cloning into '/Users/rxandrey/Tests/obs-studio/plugins/obs-vst'...
remote: Enumerating objects: 833, done.        
remote: Counting objects: 100% (161/161), done.        
remote: Compressing objects: 100% (128/128), done.        
remote: Total 833 (delta 88), reused 69 (delta 29), pack-reused 672        
Receiving objects: 100% (833/833), 648.66 KiB | 3.07 MiB/s, done.
Resolving deltas: 100% (474/474), done.
Cloning into '/Users/rxandrey/Tests/obs-studio/plugins/win-dshow/libdshowcapture'...
remote: Enumerating objects: 908, done.        
remote: Counting objects: 100% (124/124), done.        
remote: Compressing objects: 100% (81/81), done.        
remote: Total 908 (delta 82), reused 67 (delta 43), pack-reused 784        
Receiving objects: 100% (908/908), 294.22 KiB | 1.99 MiB/s, done.
Resolving deltas: 100% (629/629), done.
Submodule path 'plugins/enc-amf': checked out 'f057617ea2617b25603189a7ab72513b62c8c140'
Submodule path 'plugins/mac-syphon/syphon-framework': checked out '01b144811f6f7080b70b2d7cc729da071f86f9d7'
Submodule path 'plugins/obs-browser': checked out 'b0d687937af876b52b69c46e276b4ab601b07f0e'
Submodule path 'plugins/obs-outputs/ftl-sdk': checked out 'd0c8469f66806b5ea738d607f7d2b000af8b1129'
Submodule 'libcurl' (https://github.com/curl/curl) registered for path 'plugins/obs-outputs/ftl-sdk/libcurl'
Submodule 'libjansson' (https://github.com/akheron/jansson) registered for path 'plugins/obs-outputs/ftl-sdk/libjansson'
Cloning into '/Users/rxandrey/Tests/obs-studio/plugins/obs-outputs/ftl-sdk/libcurl'...
remote: Enumerating objects: 174175, done.        
remote: Counting objects: 100% (10/10), done.        
remote: Compressing objects: 100% (9/9), done.        
remote: Total 174175 (delta 2), reused 7 (delta 1), pack-reused 174165        
Receiving objects: 100% (174175/174175), 81.06 MiB | 2.92 MiB/s, done.
Resolving deltas: 100% (137543/137543), done.
Cloning into '/Users/rxandrey/Tests/obs-studio/plugins/obs-outputs/ftl-sdk/libjansson'...
remote: Enumerating objects: 6536, done.        
remote: Counting objects: 100% (42/42), done.        
remote: Compressing objects: 100% (34/34), done.        
remote: Total 6536 (delta 11), reused 18 (delta 8), pack-reused 6494        
Receiving objects: 100% (6536/6536), 1.76 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (3912/3912), done.
Submodule path 'plugins/obs-outputs/ftl-sdk/libcurl': checked out '44b9b4d4f56d6f6de92c89636994c03984e9cd01'
Submodule path 'plugins/obs-outputs/ftl-sdk/libjansson': checked out 'bc5741fb1ac730ead24e9bd08977fc6c248e04b0'
Submodule path 'plugins/obs-vst': checked out '8ad3f64e702ac4f1799b209a511620eb1d096a01'
Submodule path 'plugins/win-dshow/libdshowcapture': checked out '8e7a75f2bf50dce4c9ebccf362023ecc567cece1'
Updating files: 100% (2537/2537), done.
M	plugins/enc-amf
M	plugins/obs-browser
M	plugins/obs-vst
M	plugins/win-dshow/libdshowcapture
Switched to a new branch 'obs-plugin-build'
[obs-plugin] Build libobs and obs-frontend-api
  + Configuring OBS build system
  + CCache available
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OBS_VERSION: 26.1.2-modified
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/OpenGL.framework   
-- Found FFmpeg: /Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavcodec.dylib (found version "58.54.100") found components: avcodec avdevice avutil avformat 
-- Found Libcurl: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libcurl.tbd  
CMake Deprecation Warning at deps/obs-scripting/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Scripting plugin disabled
CMake Deprecation Warning at deps/libcaption/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Using system Jansson library
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found FFmpeg: /Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavformat.dylib (found version "58.29.100") found components: avformat avutil swscale swresample avcodec 
-- Using libavcodec for image loading in libobs
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/../lib/libz.tbd  
-- Could NOT find LibVLC (missing: VLC_INCLUDE_DIR) 
-- VLC video plugin disabled
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'jack'
--   Found jack, version 1.9.19
-- Found jack: /usr/local/lib/libjack.dylib
-- Using the bundled VST header.
-- Found Libx264: /Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libx264.dylib  
-- Libfdk not found - obs-libfdk plugin disabled
-- Found FFmpeg: /Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavcodec.dylib (found version "58.54.100") found components: avcodec avfilter avdevice avutil swscale avformat swresample 
-- Found FFmpeg: /Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavcodec.dylib (found version "58.54.100") found components: avcodec avutil avformat 
-- Found MbedTLS: /Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libmbedtls.dylib;/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libmbedcrypto.dylib;/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libmbedx509.dylib  
-- Found ftl-sdk: ftl outputs enabled
-- Found Libspeexdsp: /Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libspeexdsp.dylib  
-- Found AppKit: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AppKit.framework  
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_PLUGINS
    OBS_CODESIGN_LINKER

-- Build files have been written to: /Users/rxandrey/Tests/obs-studio/plugin_build
  + Building libobs and obs-frontend-api
[30/90] Building C object libobs/CMakeFiles/libobs.dir/graphics/graphics.c.o
/Users/rxandrey/Tests/obs-studio/libobs/graphics/graphics.c:2775:22: warning: incompatible integer to pointer conversion passing 'uint32_t' (aka 'unsigned int') to parameter of type 'uint32_t *' (aka 'unsigned int *'); take the address with & [-Wint-conversion]
                        graphics->device, handle);
                                          ^~~~~~
                                          &
1 warning generated.
/Users/rxandrey/Tests/obs-studio/libobs/graphics/graphics.c:2775:22: warning: incompatible integer to pointer conversion passing 'uint32_t' (aka 'unsigned int') to parameter of type 'uint32_t *' (aka 'unsigned int *'); take the address with & [-Wint-conversion]
                        graphics->device, handle);
                                          ^~~~~~
                                          &
1 warning generated.
[88/90] Linking C shared library libobs/libobs.0.dylib
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavcodec.dylib) was built for newer macOS version (17.0) than being linked (10.13)
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavutil.dylib) was built for newer macOS version (17.0) than being linked (10.13)
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libswscale.dylib) was built for newer macOS version (17.0) than being linked (10.13)
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavformat.dylib) was built for newer macOS version (17.0) than being linked (10.13)
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libswresample.dylib) was built for newer macOS version (17.0) than being linked (10.13)
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavcodec.dylib) was built for newer macOS version (20.0) than being linked (11.0)
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavformat.dylib) was built for newer macOS version (20.0) than being linked (11.0)
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libavutil.dylib) was built for newer macOS version (20.0) than being linked (11.0)
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libswscale.dylib) was built for newer macOS version (20.0) than being linked (11.0)
ld: warning: dylib (/Users/rxandrey/Tests/obs-build-dependencies/obs-deps/lib/../lib/libswresample.dylib) was built for newer macOS version (20.0) than being linked (11.0)
[90/90] Linking CXX shared library UI/obs-frontend-api/libobs-frontend-api.dylib
[obs-plugin] Build plugin obs-plugin
  + Configuring OBS plugin build system
  + CCache available
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:28 (find_package):
  By not providing "Findobs-frontend-api.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "obs-frontend-api", but CMake did not find one.

  Could not find a package configuration file provided by "obs-frontend-api"
  with any of the following names:

    obs-frontend-apiConfig.cmake
    obs-frontend-api-config.cmake

  Add the installation prefix of "obs-frontend-api" to CMAKE_PREFIX_PATH or
  set "obs-frontend-api_DIR" to a directory containing one of the above
  files.  If "obs-frontend-api" provides a separate development package or
  SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/Users/rxandrey/Tests/obs-plugintemplate/build/CMakeFiles/CMakeOutput.log".
See also "/Users/rxandrey/Tests/obs-plugintemplate/build/CMakeFiles/CMakeError.log".
  + ERROR during build step: builds_obs_plugin

**Comment by PatTheMav** [comment]
Please try again with the updated template.
