### ISSUE TITLE
macOS linker-signed issue

### ISSUE THREAD

**Issue by nikolawhallon** [obsproject/obs-plugintemplate#23]
### Operating System Info

macOS 10.15

### OBS Studio Version

Other

### OBS Studio Version (Other)

I have not modified buildspec.json, out of the box it seems to target 27.2.3

### OBS Studio Log URL

N/A

### Expected Behavior

I expected:
```
.github/scripts/build-macos.zsh
```
to build the `.plugin` file.

### Current Behavior

Currently, the build fails with:

```
FAILED: obs-plugintemplate.plugin/Contents/MacOS/obs-plugintemplate 
: && /Library/Developer/CommandLineTools/usr/bin/c++ -O2 -g -DNDEBUG -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -bundle -Wl,-headerpad_max_install_names  -o obs-plugintemplate.plugin/Contents/MacOS/obs-plugintemplate CMakeFiles/obs-plugintemplate.dir/obs-plugintemplate_autogen/mocs_compilation.cpp.o CMakeFiles/obs-plugintemplate.dir/src/plugin-main.c.o  -Wl,-rpath,/Users/browncanstudios/OBSDev/obs-build-dependencies/obs-plugin-deps/lib -Wl,-rpath,/Users/browncanstudios/OBSDev/obs-build-dependencies/obs-plugin-deps/Frameworks  /Users/browncanstudios/OBSDev/obs-build-dependencies/obs-plugin-deps/lib/libobs-frontend-api.27.dylib  /Users/browncanstudios/OBSDev/obs-build-dependencies/obs-plugin-deps/Frameworks/libobs.framework/Versions/A/libobs  /Users/browncanstudios/OBSDev/obs-build-dependencies/obs-plugin-deps/lib/QtWidgets.framework/QtWidgets  /Users/browncanstudios/OBSDev/obs-build-dependencies/obs-plugin-deps/lib/QtGui.framework/QtGui  /Users/browncanstudios/OBSDev/obs-build-dependencies/obs-plugin-deps/lib/QtCore.framework/QtCore && cd /Users/browncanstudios/OBSDev/obs-plugintemplate/build_macos-x86_64 && /bin/sh -c "codesign --force --sign \"-\" --options linker-signed \"/Users/browncanstudios/OBSDev/obs-plugintemplate/build_macos-x86_64/obs-plugintemplate.plugin\""
invalid argument "linker-signed"
ninja: build stopped: subcommand failed.
    ✖︎ script execution error

    Callstack:
    .github/scripts/build-macos.zsh:181
     .github/scripts/build-macos.zsh:188
```

### Steps to Reproduce

1. git clone git@github.com:obsproject/obs-plugintemplate.git
2. cd obs-plugintemplate
3. .github/scripts/build-macos.zsh
...

### Anything else we should know?

I have gotten builds to work by commenting out the following lines in `cmake/ObsPluginHelpers.cmake`:

```
#    if(OBS_CODESIGN_LINKER)
#      set(CMAKE_XCODE_ATTRIBUTE_OTHER_CODE_SIGN_FLAGS "-o linker-signed")
#    endif()
```
and
```
#    add_custom_command(
#      TARGET ${target}
#      POST_BUILD
#      COMMAND
#        /bin/sh -c
#        "codesign --force --sign \"-\" $<$<BOOL:${OBS_CODESIGN_LINKER}>:--options linker-signed >\"$<TARGET_BUNDLE_DIR:${target}>\""
#      COMMENT "Codesigning ${target}"
#      VERBATIM)
```

After doing this, I can successfully run `.github/scripts/build-macos.zsh` and then `.github/scripts/package-macos.zsh`. After this point, I can install the plugin via `obs-plugintemplate-1.0.0-macos-x86_64.pkg`, but my OBS does not load it, but this is likely a completely separate issue, and I'm not sure if it's relevant since getting the build to work by commenting out those lines doesn't quite feel right in the first place.

P.S. I have an interesting plugin working when I build it into obs itself, but I can't figure out how to deal with distribution, so I'm excited to use this plugin template, and I apologize if this issue isn't appropriate or is just highlighting my own ignorance :\

**Comment by PatTheMav** [comment]
Configure the CMake project with `OBS_CODESIGN_LINKER` set to `OFF` - this feature is available on macOS 11+ only.

We officially only support development for macOS on 11+ as well (given that we'd require people to also support our upcoming Apple Silicon-based versions), but with that option you should still be able to compile on 10.15.

**Comment by nikolawhallon** [comment]
> Configure the CMake project with `OBS_CODESIGN_LINKER` set to `OFF` - this feature is available on macOS 11+ only.
> 
> We officially only support development for macOS on 11+ as well (given that we'd require people to also support our upcoming Apple Silicon-based versions), but with that option you should still be able to compile on 10.15.

Awesome, thanks! Will try, but also happy to move to macOS 11+.

**Comment by nikolawhallon** [comment]
Does this need to updated? It claims macOS 10.13 and above is supported (Option A) or macOS 10.15 (Option B):

https://obsproject.com/wiki/build-instructions-for-mac

I guess that is for the whole OBS app, and not the plugin template, but I don't see in the README the minimum supported version.

**Comment by PatTheMav** [comment]
There is the minimum platform we support for _running_ OBS (which so far has been macOS 10.13 but will be increased to macOS 10.15) and the minimum platform for _compiling_ OBS (which also implies which tooling support we can assume) which has been 10.15 and will be increased to macOS 11.0.

The feature is enabled by default for that reason (also because we added support for Apple Silicon) but it can be disabled for people who cannot update. That requires manually managing their CMake build configuration however.

The documentation will be updated in due time as well, as it's usually one of the less glitzy aspects of development..

**Comment by nikolawhallon** [comment]
@PatTheMav thanks! I really appreciate it, makes perfect sense.
