### ISSUE TITLE
how to use branch version of obs-studio

### ISSUE THREAD

**Issue by jwang0512** [obsproject/obs-plugintemplate#24]
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

NA

### Expected Behavior

NA

### Current Behavior

NA

### Steps to Reproduce

changed buildspec.json to 
        "obs-studio": {
            "version": "27.2.4",
            "repository": "https://github.com/obsproject/obs-studio.git",
            "branch": "release/27.2",
            "hash": "2ac9f83cb662692d34874ee1fd17ad7675597215"
        },

and the build throws error : fatal: 'release/27.2' is not a commit and a branch 'test' cannot be created from it
btw where can i find the hash of obs-studio?

Thanks

**Comment by jwang0512** [comment]
set branch to "branch": "origin/release/27.2" seems worked.

**Comment by PatTheMav** [comment]
The branch needs to be reachable via the reference `refs/remotes/origin/<BRANCH_NAME>`. You can find commit hashes by running `git rev-parse HEAD` on your checkout or via many other methods.

As for the build errors, we'd need the actual error messages to be able to investigate.

**Comment by RytoEX** [comment]
As mentioned above, we'd need the actual error messages to be able to investigate. We've closed this as a stale report.
