### ISSUE TITLE
Wrong packaging directory on macos

### ISSUE THREAD

**Issue by summershrimp** [obsproject/obs-plugintemplate#56]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

Nope

### Expected Behavior

Generate plugin pkg installer file.

### Current Behavior

packages failed to packaging plugin to pkg installer file.

### Steps to Reproduce

1. run ./.github/script/package-macos.zsh

### Anything else we should know?

https://github.com/obsproject/obs-plugintemplate/blob/c85ef7715130a11ec6718267c8d1ed1fc36f6b75/cmake/bundle/macos/installer-macos.pkgproj.in#L66

at installer-macos.pkgproj.in , @RELATIVE_INSTALL_PATH@ is expanded to `build_x64/install` 

but at .build.zsh, plugin is installed to `release`

https://github.com/obsproject/obs-plugintemplate/blob/c85ef7715130a11ec6718267c8d1ed1fc36f6b75/.github/scripts/.build.zsh#L243

so package failed

**Comment by summershrimp** [comment]
It seems working on CI, but not working on my local computer.

**Comment by progressmedia** [comment]
Agreed. It is not working for me either and the very rough translations from readme don't exactly help.

**Comment by paulpv** [comment]
Might this be fixed by https://github.com/obsproject/obs-plugintemplate/pull/41/files ?

**Comment by RytoEX** [comment]
#41 was closed by #76, so this should be resolved.
