### ISSUE TITLE
Cannot find libobs

### ISSUE THREAD

**Issue by AndersBillLinden** [obsproject/obs-plugintemplate#57]
Where do I find libobs? Seems to not be included or linked to via git submodule?

**Comment by Fenrirthviti** [comment]
When submitting a bug report, please do not delete the template. It sends the message that following our process isn't worth your time.

Since this sounds like a support issue, please use the forums or Discord for more assistance.

**Comment by AndersBillLinden** [comment]
I am sorry for that. I first filled in the template questions and then simplified the issue to not reiterate any information. The problem is that I did not find libobs. That problem could other users possibly also be facing so the issue is an improvement suggestion that the information could be complemented.

**Comment by rogueyoshi** [comment]
@AndersBillLinden double check and see if you installed the build toolchain correctly. I had a similar issue and deleted my entire pre-existing toolchain to fix it.

**Comment by AndersBillLinden** [comment]
> @AndersBillLinden double check and see if you installed the build toolchain correctly. I had a similar issue and deleted my entire pre-existing toolchain to fix it.

Oh, I only installed cmake. Maybe thats a bit optimistic...
