### ISSUE TITLE
RFC: Change CI to use GitHub Actions

### ISSUE THREAD

**Issue by cpyarger** [obsproject/obs-plugintemplate#8]
# Summary

Currently, the plugin template uses Azure Pipelines.  I propose the default CI pipeline use GitHub Actions

# Motivation

- Since most of the workflow is on GitHub anyway, It makes more sense to use the Github Actions pipeline. 
- No need to sign up for yet another account in order to do CI

# Drawbacks
Personally, I can't think of any 

# Additional Information
The base obs-studio project seems to be using GitHub actions now, as do many of the other plugins I have looked at. 
ex.
https://github.com/cpyarger/obs-midi
https://github.com/Palakis/obs-websocket

**Comment by bontibon** [comment]
This has been completed.

**Comment by RytoEX** [comment]
This was completed in #15.
