### ISSUE TITLE
QWebSocket doesn't working

### ISSUE THREAD

**Issue by zaxo7** [obsproject/obs-plugintemplate#85]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

http://pastebin.fr/129483

### Expected Behavior

i successfully added QWebSocket dependency and it's dll, when i run the code inside a Qt application it connects to the socket with no problem, but when i add it to the plugin, when i call websocket.open(url) nothing happens.

### Current Behavior

the socket never connects 

### Steps to Reproduce

1.
2.
3.
...
in the obs_module_load create a simple websocket object then call the open method with a url

**Comment by zaxo7** [comment]
edit:
i found the problem, after trying to connect to the socket when i check the error string i get SSL Sockets are not supported on this platform. from QWebSocket
how can i add ssl support

**Comment by zaxo7** [comment]
edit:
i found the problem, after trying to connect to the socket when i check the error string i get SSL Sockets are not supported on this platform. from QWebSocket
how can i add ssl support

**Comment by RytoEX** [comment]
We don't ship QWebSocket and we don't provide support for it.
