### ISSUE TITLE
Is GPL2 the required license for all plugins developed using this template.

### ISSUE THREAD

**Issue by FiniteSingularity** [obsproject/obs-plugintemplate#87]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

N/A

### Expected Behavior

I am currently developing a plugin I would like to release for OBS.  I've noticed that both the OBS source and this plugin template use the GPL2 license.  As this is a template/boilerplate generation of a set of cmake build scripts, is the GPL2 LICENSE file that is automatically generated the license that any plugin created with this template is expected to use?  Or am I able to license my own plugin code with the license of my choosing (e.g.- MIT)? 

### Current Behavior

N/A

### Steps to Reproduce

N/A

**Comment by RytoEX** [comment]
Any program that links against libobs must be GPL v2+ compatible (libobs is GPL v2+, while OBS Studio as a whole is effectively GPL v3+). If you use files from this repo in your repo, their license is as advertised. If you create new files for your plugin and link against libobs, they must be GPL v2+ compatible.

**Comment by FiniteSingularity** [comment]
Thank you for letting me know.  Will stick with GPL2.

**Comment by RytoEX** [comment]
> Thank you for letting me know. Will stick with GPL2.

Note that GPLv2 (SPDX: GPL-2.0 or GPL-2.0-only) and GPLv2+ (SPDX: GPL-2.0-or-later) are slightly different. Be sure to understand the difference in how to mark/identify your files. The headers in this repo in the files in `src` are GPLv2+.
