### ISSUE TITLE
macOS build of plugin excludes files from libobs's util directory

### ISSUE THREAD

**Issue by nhielost** [obsproject/obs-plugintemplate#88]
### Operating System Info

macOS 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.2

### OBS Studio Log URL

N/A

### Expected Behavior

My plugin should build without errors from ```libobs``` on macOS using GitHub Actions.

### Current Behavior

The GitHub Actions build succeeds for all OSes except for macOS. A "file not found" error from the line ```#include <util/config-file.h>``` is why the build stops.

![Error](https://github.com/obsproject/obs-plugintemplate/assets/64743457/5fe1c66a-64e1-4851-872b-9eca718b92cd)

More testing indicated that some files in the resulting ```libobs/util``` include directory were missing, as shown below.

![Missing Files](https://github.com/obsproject/obs-plugintemplate/assets/64743457/ffc56978-de44-4249-8712-a5ee3a25c798)

### Steps to Reproduce

1. Generate from this repo.
2. Add ```#include <util/config-file.h>``` to the source code.
3. Commit and push.
4. The macOS run fails.

### Anything else we should know?

The other ```libobs``` include files and directories are all there. It is only the ```util``` directory that is having this problem. Also, this has occurred every time I have run the workflow - it is not a one-time thing.

**Comment by gxalpha** [comment]
This should be fixed with OBS 30.

**Comment by ShigemoriHakura** [comment]
Is this bug fixed? I'm using 30.0.0-rc1 but still has this issue both on Actions and local.

**Comment by gxalpha** [comment]
@ShigemoriHakura did you change the buildspec to point to the RC? If so, could you post the error (or link the repo)?

**Comment by ShigemoriHakura** [comment]
> @ShigemoriHakura did you change the buildspec to point to the RC? If so, could you post the error (or link the repo)?

fixed, now I can build the project properly.
