### ISSUE TITLE
RFC: Create Multiple Plugin Templates

### ISSUE THREAD

**Issue by cpyarger** [obsproject/obs-plugintemplate#9]
# Summary

As there are multiple types of plugins, It would make sense to have a basic template for each of those various types. 

# Motivation

I know I have helped a couple of people out now, getting basic functions such as a menu setup, with a plugin setup window dialog started. 

# Drawbacks

PluginTemplate would most likely need to be changed to give links and descriptions for each of the plugin templates

# Additional Information

**Comment by RytoEX** [comment]
I've discussed this with @PatTheMav and others off-thread and we're going to close this as out-of-scope for our plans for this repo. While it is an interesting idea, we need to balance the complexities of this repo against the maintenance burden such complexities would generate.
